# Execute Arduino Lint automatically upon push or pull request
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1.0.2
        with:
          path: ./software/ogd_pico/
          project-type: sketch # Only Check Arduino Sketches
          library-manager: update
          compliance: specification #strict
